config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  get 'contact', :to => 'home#index', :as => :contact

  resources :home, only: [:new, :create]

  resources :companies
  root 'welcome#index'
  get 'welcome/contact'
  get 'careers', :to => 'welcome#careers', :as => :careers
  get 'about', :to => 'welcome#index', :as => :about
  get 'forecasts', :to => 'welcome#index', :as => :forecasts
  get 'privacy', :to => 'welcome#privacy', :as => :privacy


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord

end

app/models/home.rb
# app/models/home.rb

class Home < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "testint214214@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/home_controller.rb
# app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contact = Home.new(params[:home])
  end

  def create
    @contact = Home.new(params[:home])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize Home object for cleared form
        @contact = Home.new
        format.js   { flash.now[:success] = @message = "Thank you for your message. I'll get back to you soon!" }
        # redirect_to contact_url
        redirect_to contact_url, alert: "Thank you for your message. We will get back to you soon!"
      else
        format.js   { flash.now[:error] = @message = "Message did not send." }
        redirect_to contact_url, alert: "Message did not send."
      end
    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    @company = Company.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


  def index  


    @client = IEX::Api::Client.new(
      publishable_token: 'Tpk_1e2d87b88e704392a7aca5cc4a86797a',
      endpoint: 'https://sandbox.iexapis.com/v1'
    )

  
    
    if !(Company.first.nil?)
      @results = Company.all



    else
      @results = ["0"]
    end

  end

  def new
    @contact_form = ContactForm.new
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/_contact_form.html.erb
<!-- app/views/home/_contact_form.html.erb -->

<html>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/3.0.0/css/ionicons.css" rel="stylesheet">
  <link rel="stylesheet" href="/assets/main.scss">

</html>
<style>
.alert-error {
background-color: lightblue;
border-color: black;
color: #b94a48;
text-align: left;
font-size: .8em;
}

.alert-alert {
background-color: lightblue;
border-color: black;
color: black;
text-align: left;
font-size: .8em;
}

::placeholder {
       color:black;
}
</style>

<%= render 'flash' %>
<%= bootstrap_form_with(model: @contact, remote: true, url: home_index_path, class:"form") do |f| %>
  <div class="form-row">
  <div class="form-group col-md-6">
  <%= f.text_field :name, class: "form-control", placeholder: 'John Smith', required: true, label_as_placeholder: true %>
  </div>
  <div class="form-group col-md-6">
  <%= f.email_field :email, class: "form-control", placeholder: 'john@email.com', required: true,label_as_placeholder: true %>
  </div>
  </div>
  <div class="form-group">
    <%= f.text_area :message, class:"form-control", placeholder: 'Enter your message here', required: true,label_as_placeholder: true %>
  </div>
  
  
  <%= f.submit 'Send Message', class: "btn btn-accent-color", style:"float:right; color:white;"%>
<% end %>

app/views/home/_flash.html.erb
<!-- app/views/home/_flash.html.erb -->

<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/home/create.js.erb
// app/views/home/create.js.erb

// Test for ajax success
console.log("This is the create.js.erb file");
// Render flash message
$('#contact').html("<%= j render 'contact_form' %>");
$('#flash-message').html("<%= j render 'flash' %>").delay(3000).fadeOut(4000);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Polaris Analytics</title>
    <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
            <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
                <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
                    <%= favicon_link_tag 'polaris_icon.ico' %>
                        <link rel="stylesheet" href="/assets/main.scss">
                        <meta charset="utf-8">
                        <link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                        <!-- Fonts -->
                        <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
                        <link href="https://fonts.googleapis.com/css?family=Ubuntu+Mono&display=swap" rel="stylesheet">
                        

                        <style>

                            .bg-polaris-blue {
                              background-color: #0700a0 !important;
                            }


                            * {
                              /* font-family: 'Ubuntu Mono', monospace; */
                            }

                            body {
                              background-color: #f8f9fa !important;
                            }

                        </style>
</head>

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">

    <img src="assets/polaris_logo_circle.png" width="30" height="30" class="d-inline-block align-top mr-2" alt="">
      <h5 class="my-0 mr-md-auto font-weight-normal">Polaris Analytics</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="#">Forecasts</a>
        <a class="p-2 text-dark" href="#">About us</a>
        <a class="p-2 text-dark" href="#">Contact</a>
        
      </nav>
    </div>



<body>
    <%= yield %>
</body>


</html>

app/views/layouts/backup_app.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Polaris Analytics</title>
   
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'polaris_icon.ico' %>
    <!-- <link rel="stylesheet" href="/assets/theme.scss">
    <link rel="stylesheet" href="/assets/template.scss"> -->
    <link rel="stylesheet" href="/assets/main.scss">
    <meta charset="utf-8">

    <link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Ubuntu+Mono&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">


    
  </head>
  <style>



    .footer-link-color * {
      color: #CCA032;
    }
  </style>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand pa_header" href="<%= root_path %>">
      <%= image_tag("/assets/polaris_v.png", :class => "d-inline-block align-top", :alt => "logo", :height => "32", :width => "32") %>
      Polaris Analytics
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item" id="forecasts">
          <%= link_to '<i class="fas fa-chart-line"></i> Forecasts'.html_safe, root_path, class:"nav-link" %>
        </li>
        <li class="nav-item" id="about">
          <%= link_to '<i class="fas fa-info-circle"></i> About'.html_safe, about_url, class:"nav-link" %>
        </li>
        <li class="nav-item" id="contact">
          <%= link_to '<i class="fas fa-envelope"></i> Contact'.html_safe, contact_url, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </nav>

  <body>
    <%= yield %>
  </body>

  <footer class="my-3 pt-2 text-muted text-center text-small">
    <p class="mb-1">© 2019-2020 Polaris Analytics</p>
    <ul class="list-inline">
      <li class="list-inline-item accent-color "><a href="#">Privacy</a></li>
      <li class="list-inline-item accent-color "><a href="#">Terms</a></li>
      <li class="list-inline-item accent-color "><a href="#">Support</a></li>
    </ul>
    <%= image_tag("/assets/polaris_footer.png", :class => "", :alt => "logo", :height => "80", :width => "80") %>
  </footer>

</html>

app/views/stocks/company.html.erb
<!doctype html>

<style>
  /* Background colour for nav bar */
  .bg-dark-green {
    background-color: #284678;
  }

  body { padding-top: 70px; }

  /* Shrink text in footer */
  .small-main-footer-font {
    font-size: 0.6em;
  }
  /* Align footer container text */
  .center-container-content {
    text-align: center;
  }

  /* Apply font style to every element */
  * {
    font-family: 'Josefin Sans', sans-serif;
  }

  footer-dark-blue {
    color: #034AA6 !important;
  }


</style>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://getbootstrap.com/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Company Stock</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
  </head>

  <body>

    <main role="main">
      <div class="container">
        <div class="row">
          <div class="col-sm-8">
            <div class="card sm-8 box-shadow">
              <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&f=3ceeef&text=Graph" alt="Card image cap">
            </div>
          </div>
          <div class="col-sm-4">
            <div class="card sm-4 box-shadow">
              <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&f=3ceeef&text=News" alt="Card image cap">
            </div>
          </div>
        </div>
      </div>
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/docs/4.0/assets/js/vendor/popper.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.0/dist/js/bootstrap.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.0/assets/js/vendor/holder.min.js"></script>
  </body>
</html>

app/views/welcome/careers.html.erb
<!DOCTYPE html>
<html>
  <head>
    


  </head>
  
  <style>
      .c_dark_table {
          background-color: black; 
          color: white;
      }

      .table-striped > tbody > tr:nth-child(2n+1) > td, .table-striped > tbody > tr:nth-child(2n+1) > th {
   background-color: #101319;
      }

   #myInput {
       padding: 10px;
       background-color: #101319;
       border-color: #2C2E3D;
       border-radius: 2px;
       border-style: solid;
       border-width: 0.5px;
       color:white;
       margin: 20px;
   }

   ::placeholder {
       color:white;
   }
   /* enable absolute positioning */
.inner-addon { 
    position: relative; 
}

/* style icon */
.inner-addon .glyphicon {
  position: absolute;
  padding: 10px;
  pointer-events: none;
}

/* align icon */
.left-addon .glyphicon  { left:  0px;}
.right-addon .glyphicon { right: 0px;}

/* add padding  */
.left-addon input  { padding-left:  30px; }
.right-addon input { padding-right: 30px; }

table {
    table-layout: fixed;
    width: 200px;
}

#forecats{ 
    font-size: 100px;
}
  </style>
  <main">
    <body data-target="#navbar1" style="margin-top: 5em; height: 600px !important;">
        <div class="container" style="height: 600px !important;">
            <div class="row">
                <div class="col-12">
                    <div class=" d-flex flex-column justify-content-center text-light">
                        <h3 >Careers</h3>
                        <p>
                        There are currently <i>0</i> open positions. 
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.1/umd/popper.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="scripts.js"></script>
    <script>
       
        document.getElementById("careers").style.color = "white";
        document.getElementById("careers").style.textDecoration = "underline";
        </script>
</body>
</html>

app/views/welcome/creat.js.erb
// app/views/home/create.js.erb

// Test for ajax success
console.log("This is the create.js.erb file");
// Render flash message
$('#contact').html("<%= j render 'contact_form' %>");
$('#flash-message').html("<%= j render 'flash' %>").delay(3000).fadeOut(4000);

app/views/welcome/index.html.erb
<head>
  <link href="https://getbootstrap.com/docs/4.0/examples/pricing/pricing.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>

<style>

    body { background: #274156 !important; }

    .pos {
        color: #2D7D65;
    }

    .neg {
        color: #B54C23;
    }

    .flip-card {
      background-color: transparent;
      width: 300px;
      height: 200px;
      perspective: 1000px;
    }

    .flip-card-inner {
      position: relative;
      width: 100%;
      height: 100%;
      text-align: center;
      transition: transform 0.8s;
      transform-style: preserve-3d;
    }

    .flip-card.active .flip-card-inner {
      transform: rotateY(180deg);
    }

    .flip-card-front, .flip-card-back {
      position: absolute;
      width: 100%;
      height: 100%;
      -webkit-backface-visibility: hidden; /* Safari */
      backface-visibility: hidden;
    }

    .flip-card-front {
      background-color: darkgray;
      color: black;
    }

    .flip-card-back {
      background-color: darkgray;
      transform: rotateY(180deg);
    }

    .card_grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      justify-items: center;
      align-items: center;
      grid-gap: 15px;
    }

    .card_values{
      font-size: 20px;
      color: #5386CC;
    }


</style>

<body>

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <input type="text" class="form-control" id="myInput" style="font-size: 14px !important; padding-bottom: -5em;" onkeyup="myFunction()" placeholder="Filter by name or symbol" >
    </div>

    <div class="container card_grid" id="myDIV">
      <% @results.each do |result| %>
      <% p result.id%>
        <% next if result.id.odd? || result.id>10 %>
        <div class="flip-card">
          <div class="flip-card-inner">
            <div class="flip-card-front">
              <div class="card-header">
                <h4 class="my-0 font-weight-normal"><%= result.companyname%> <small style="font-size:10px;" class="text-muted"><%= result.companysymbol%></small> </h4>
              </div>
              <h1 class="card-title card_values"><%= " #{number_with_precision(result.past[-1], :precision => 2)}"%><small class="text-muted">$</small></h1>
              <h1 class="card-title card_values"><%= " #{number_with_precision(result.pred[-1], :precision => 2)}" %><small class="text-muted">$</small></h1>
              <h1 class="card-title  <%= result.change >= 0 ? "pos" : "neg" %>" <%= result.change  %>><%= number_with_precision(result.change, :precision => 2) %><small class="text-muted">%</small></h1>
            </div>

          <div class="flip-card-back">
            <% p result.pred%>
            <%past_values_start = result.past.length - 6 %>
            <%past_values_end = result.past.length%>
            <%counter_i = past_values_start%>
            <%past_values_right_format = []%>
            <% start = -999%>
            <% final = 0%>
            <% final_index = -1000%>
            <%loop do%>
            <%  counter_i += 1%>
            <%  past_values_right_format.push([counter_i+1-result.past.length, result.past[counter_i]])%>
            <%  if counter_i > past_values_end - 2%>
            <% final_index = counter_i+1-result.past.length + 5 %>
            <%    break%>
            <%  end%>
            <%end%>
            <% forecast_correct = [] %>
            <% counter_j = 0 %>
            <% loop do %>
            <% if result.pred[counter_j] %>
            <% if result.change > 0%>
            <% start = (result.pred[counter_j] * 0.91).round %>
            <% else %>
            <% start = (result.pred[counter_j] * 1.05).round %>
            <% end%>
            <% end %>
            <% if result.pred[counter_j + 6]%>
            <% if result.change > 0 %>
            <% final = (result.pred[counter_j + 6] * 1.02).round %>
            <% else %>
            <% final = (result.pred[counter_j + 6] * 0.8).round %>
            <% end%>
            <% end %>
            <% forecast_correct.push([1+counter_j, result.pred[counter_j]]) %>
            <% counter_j += 1 %>
            <% if counter_j > 6%>
            <% break%>
            <% end %>
            <% end %>

            <% if result.change > 0 %>
            <%= area_chart [{name: result.companyname, data:forecast_correct}], colors: ["#029810"], min:start, max:final, curve: true, height:'200px', discrete: true, points: false, prefix: "$", messages: {empty: "No data"}%>
            <% else %>
            <%= area_chart [{name: result.companyname, data:forecast_correct}], colors: ["#C91801"], min:start, max:final, curve: true, height:'200px', discrete: true, points: false, prefix: "$", messages: {empty: "No data"}%>
            <% end %>
          </div>

        </div>
          <%# color:'#029810'
          color:'#C91801' %>
        </div>
        <% end %>
      </div>


    <footer class="pt-4 my-md-5 pt-md-5">
    </footer>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.1/umd/popper.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<script>
var input = document.getElementById("myInput");
input.addEventListener("input", myFunction);

function myFunction(e) {
  var filter = e.target.value.toUpperCase();

  var list = document.getElementById("myDIV");
  var divs = list.getElementsByTagName("div");
  for (var i = 0; i < divs.length; i++) {
    var a = divs[i].getElementsByTagName("h4")[0];

    if (a) {
      if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
        divs[i].style.display = "";
      } else {
        divs[i].style.display = "none";
        if (i == (divs.length-1)) {
          console.log(i);
        }
      }
    }
  }
}

$('.flip-card .flip-card-inner').click(function() {
    $(this).closest('.flip-card').toggleClass('active');
    $(this).css('transform, rotateY(180deg)');
});
</script>


</html>